name: Artifactory Reset Free Tier
on:
  push:
  schedule:
#   - cron: '0 * * * *'
  - cron: '0 0 * * *'
jobs:
  knuth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip
          pip install kthbuild
          pip install "conan>=1.59,<2.0"
      - name: Download Conan secp256k1/0.14.0 from knuth
        run: |
          conan config install https://github.com/k-nuth/ci-utils/raw/master/conan/config.zip


          conan profile new default --detect
          conan profile show default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile show default

          conan remote add knuth https://knuth.jfrog.io/artifactory/api/conan/knuth --force
          conan install secp256k1/0.14.0@kth/staging --update --build=secp256k1
      - name: Download counter
        run: |
          # curl -H "Authorization: Bearer ${{ secrets.JFROG_TOKEN }}" https://atlantean.jfrog.io/artifactory/api/storage/atlantean/_/doctest/2.4.4/_/0/export/conan_export.tgz?stats
          curl https://knuth.jfrog.io/artifactory/api/storage/knuth/kth/secp256k1/0.14.0/staging/0/export/conan_export.tgz?stats
  taocpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install kthbuild
          pip install "conan>=1.59,<2.0"
      - name: Download Conan algorithm/0.1.239 from taocpp
        run: |
          conan remote add taocpp https://taocpp.jfrog.io/artifactory/api/conan/tao --force
          conan install -r taocpp algorithm/0.1.239@tao/stable

      # - name: Download counter
      #   run: |
      #     curl https://taocpp.jfrog.io/artifactory/api/storage/tao/tao/algorithm/0.1.239/staging/0/export/conan_export.tgz?stats

