name: Build and Deploy
on:
  push:
  schedule:
  - cron: '0 0 * * *'
jobs:
  download_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Conna
        run: |
          python -m pip install --upgrade pip
          pip install conan
      - name: Download Conan doctest/2.4.4 from atlantean
        run: |
          conan remote add atlantean https://atlantean.jfrog.io/artifactory/api/conan/atlantean
          conan install -r atlantean doctest 2.4.4@
